name: mmocr
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - pytorch=1.7.0=py3.7_cuda11.0*
  - torchvision=0.8.0=py37_cu110*
  - cudatoolkit=11.0
  - numpy

  - pip:
    - https://download.openmmlab.com/mmcv/dist/cu110/torch1.7.0/mmcv_full-1.3.4-cp37-cp37m-manylinux1_x86_64.whl
    - mmdet==2.11.0
    - Polygon3
    - pyclipper
    - imgaug
    - lmdb
    - matplotlib
    - numba>=0.45.1
    - rapidfuzz
    - scikit-image
    - six
    - terminaltables
    - asynctest
    - codecov
    - flake8
    - isort
    - kwarray
    - pytest
    - pytest-cov
    - pytest-runner
    - ubelt
    - xdoctest >= 0.10.0
    - yapf
    - git+https://github.com/open-mmlab/mmocr.git@main

