Collections:
- Name: PSENet
  Metadata:
    Training Data: ICDARDataset
    Training Techniques:
      - SGD with Momentum
    Training Resources: 8x NVIDIA V100 GPUs
    Architecture:
      - FPN
  Paper: https://arxiv.org/abs/1806.02559
  README: configs/textdet/psenet/README.md

Models:
  - Name: psenet_r50_fpnf_600e_ctw1500
    In Collection: PSENet
    Config: configs/textdet/psenet/psenet_r50_fpnf_600e_ctw1500.py
    Metadata:
      Training Data: CTW1500
    Results:
      - Task: Instance Segmentation
        Dataset: CTW1500
        Metrics:
          hmean: 0.784
    Weights: https://download.openmmlab.com/mmocr/textdet/psenet/psenet_r50_fpnf_600e_ctw1500_20210401-216fed50.pth

  - Name: psenet_r50_fpnf_600e_icdar2015
    In Collection: PSENet
    Config: configs/textdet/psenet/psenet_r50_fpnf_600e_icdar2015.py
    Metadata:
      Training Data: ICDAR2015
    Results:
      - Task: Instance Segmentation
        Dataset: ICDAR2015
        Metrics:
          hmean: 0.807
    Weights: https://download.openmmlab.com/mmocr/textdet/psenet/psenet_r50_fpnf_600e_icdar2015-c6131f0d.pth

  - Name: psenet_r50_fpnf_600e_icdar2017
    In Collection: PSENet
    Config: configs/textdet/psenet/psenet_r50_fpnf_600e_icdar2017.py
    Metadata:
      Training Data: ICDAR2017
    Results:
      - Task: Instance Segmentation
        Dataset: ICDAR2017
        Metrics:
          hmean: 0.847
    Weights: https://download.openmmlab.com/mmocr/textdet/psenet/psenet_r50_fpnf_600e_icdar2015_pretrain-eefd8fe6.pth
